example:
  property: "I AM THE DEFAULT"
management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  cloud:
    config:
      override-none: true
      override-system-properties: false
