example: 
  property: "I AM THE DEFAULT"
management: 
  endpoints: 
    enabled-by-default: true
    web: 
      exposure: 
        include: "*"
spring: 
  database: 
    driverClassName: org.postgresql.Driver
  jpa: 
    database: POSTGRESQL
    hibernate: 
      ddl-auto: none
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties: 
      hibernate: 
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  cloud:
    config:
      allow-override: true
      override-none: true
      override-system-properties: false
