example: 
  property: "{cipher}AgBD/pRLbmzsJj2oeP37Kpjv7t6QdY9u8qtQuX0awTpdb3+hFueULfNKtzvzBu8ioU+S4tK7XQTT+tOBy4gSg78vBrVb2Dg+RaTK0sTANLRUMZPx4mKXvi9UUYIQKqdnFOi6gcGeuSgnP+24I0wa9aapf7nkFy5Dv8HgOr92J9L59asHSUoLfsY6IoQoLCeR6iqoTQGx5S4oVauRZOsTbMJjxblTKurdDRy94CxpTigghc3VgT/2BOc0fxfYju7rHvsWZmvPS9y5eMHgNvoLRivArbPtftUW129QmxhL4wit80fx31qUmP4tZoUMZrZiVIm5ZccjKXSDI5v6X8xPBK8a0i5UFjkuLAUuydJfLWeY5ifTKVXGKSOb/jsIbEVm6PYvk/QegcTsipF0kpSUTFFCzDz5QKbxHj5ZxU+EGrS13jnL8mVEhUvQz/nmVpYOuqV1evJ8SNEVBoEiZDEruFpaQ3QEFLevk8l970s7OO4eLcjHBeBi4+r2/fKT4iMEeU8Cof9aGfM/wOi9m9EA+x3QNVzpFTjUE5lIh162uirORHyRhqcUrmeOoOSgIb9J8PZcQyPlKJey4mD8Bpm5K8BFre9erUzr8lh70VoPoGEq6MPWM5uy7tnjMmVJYRApkLUSeRAezhdGcxRMS0/59hF27psaAhdFyjuyfVf2Vh7i35PnAAZHi2KmbJ1xlrQ3u6G07TLpz+JtOTkof+UDP3MA"
spring: 
  datasource: 
    password: postgres
    url: "jdbc:postgresql://database:5432/musketeer_dev"
    username: postgres
